apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-shriram
  labels:
    app: shriram
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shriram
  template:
    metadata:
      labels:
        app: shriram
    spec:
      containers:
      - name: my-app
        image: prod-acr-shriram.azurecr.io/app:v1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name:  prod-shriram-service
spec:
  selector:
    app: shriram
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
