name: Deploy to AKS

on:
  push:
    branches:
      - main
      - prod
      - uat

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Azure CLI
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Build and Push Docker Image to ACR
    - name: Build and Push Docker Image
      env:
        ACR_NAME: ${{ secrets.ACR_NAME }}
        IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
        TAG: prod
      run: |
        az acr login --name $ACR_NAME
        docker build -t $ACR_NAME/$IMAGE_NAME:$TAG .
        docker push $ACR_NAME/$IMAGE_NAME:$TAG

    # Authenticate AKS with ACR
    - name: Attach ACR to AKS
      env:
        RESOURCE_GROUP: DC-ShriramONE-C-IND
        AKS_CLUSTER_NAME: aks-shriramone-prod-ci-dns-sc7i2hbd.hcp.centralindia.azmk8s.io
        ACR_NAME: prodacrshriram.azurecr.io
      run: |
        az aks update -n $AKS_CLUSTER_NAME -g $RESOURCE_GROUP --attach-acr $ACR_NAME

    # Deploy to AKS
    - name: Deploy to AKS
      env:
        RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
        AKS_CLUSTER_NAME: ${{ secrets.AKS_CLUSTER_NAME }}
        ACR_NAME: ${{ secrets.ACR_NAME }}
        IMAGE_NAME:  ${{ secrets.IMAGE_NAME }}
        TAG: prod
      run: |
        az aks get-credentials --resource-group $RESOURCE_GROUP --name $AKS_CLUSTER_NAME
        kubectl apply -f deployment.yaml

    # Verify Deployment
    - name: Verify Deployment
      run: |
        kubectl get pods
        kubectl get service prod-shriram-service
